# Uncomment the next line to define a global platform for your project
platform :ios, '14.1'

target 'Radom' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Radom
  pod 'Introspect'

end
